name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
 
    - name: configure
      run: cmake -B build -S .
 
    - name: make
      run: cmake --build build
 
    - name: test
      working-directory: build
      run: ctest --output-on-failure
